const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const money = v => `₹${Number(v||0).toFixed(1)} LPA`;
const fmtDate = v => v ? new Date(String(v).replace(' ','T')).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}) : '-';
const fmtDateTime = v => v ? new Date(String(v).replace(' ','T')).toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}) : '-';
const api = async (url, options={}) => { const res=await fetch(url,{credentials:'same-origin',...options}); let data; try{data=await res.json()}catch{throw new Error('Server returned an invalid response.')} if(!res.ok || data.success===false) throw new Error(data.message||'Request failed.'); return data; };
const post = (url,data) => api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
const toast = (message,error=false) => { const el=$('#toast'); if(!el)return; el.textContent=message; el.className='toast show'+(error?' error':''); setTimeout(()=>el.className='toast',2800); };
const setMsg=(el,message,error=false)=>{if(!el)return;el.textContent=message;el.className='form-message '+(error?'error':'success');};
const formObj = form => Object.fromEntries(new FormData(form).entries());
const statusClass = s => ({'Selected':'selected','Rejected':'rejected','Shortlisted':'shortlisted','Aptitude Cleared':'aptitude','Technical Cleared':'technical','HR Cleared':'hr','Pending':'pending','Open':'open'}[s]||'');

async function checkSession(expectedRole){ const d=await api('php/auth.php?action=session'); if(!d.logged_in){location.href='login.html';return null;} if(expectedRole && d.role!==expectedRole){location.href=d.role==='admin'?'admin-dashboard.html':'student-dashboard.html';return null;} return d; }
async function logout(){ try{await api('php/auth.php?action=logout')}finally{location.href='login.html'} }

function setupPublic(){
  const drives=document.querySelector('#drives'); if(!drives)return;
}
function setupAuth(){
  const login=$('#loginForm'); if(login) login.addEventListener('submit',async e=>{e.preventDefault();const f=formObj(login);const msg=$('#loginMessage');try{setMsg(msg,'Signing in...');const d=await post('php/auth.php?action=login',f);setMsg(msg,'Login successful.');location.href=d.redirect}catch(err){setMsg(msg,err.message,true)}});
  const reg=$('#registerForm'); if(reg) reg.addEventListener('submit',async e=>{e.preventDefault();const f=formObj(reg);if(f.password!==f.confirm_password)return setMsg($('#registerMessage'),'Passwords do not match.',true);if(!/^[0-9]{10}$/.test(f.phone))return setMsg($('#registerMessage'),'Phone number must contain exactly 10 digits.',true);try{const d=await post('php/auth.php?action=register',f);setMsg($('#registerMessage'),d.message);reg.reset();setTimeout(()=>location.href='login.html',1000)}catch(err){setMsg($('#registerMessage'),err.message,true)}});
}
function setupNavigation(){
  $$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>showSection(btn.dataset.section)));
  $$('[data-goto]').forEach(btn=>btn.addEventListener('click',()=>showSection(btn.dataset.goto)));
  $$('[data-logout]').forEach(btn=>btn.addEventListener('click',logout));
  $('#mobileMenu')?.addEventListener('click',()=>$('#sidebar')?.classList.toggle('open'));
}
function showSection(name){
  $$('.dash-section').forEach(s=>s.classList.toggle('active',s.id===`section-${name}`));
  $$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===name));
  $('#sidebar')?.classList.remove('open');
  if(window.dashboardType==='student') loadStudentSection(name); else if(window.dashboardType==='admin') loadAdminSection(name);
}

let studentState={profile:null,drives:[],applications:[],interviews:[],results:[],notifications:[]};
async function initStudent(){
  const session=await checkSession('student'); if(!session)return; window.dashboardType='student';
  $('#welcomeName').textContent=`Welcome, ${session.name}`;$('#headerUserName').textContent=session.name;$('#headerAvatar').textContent=(session.name||'S').charAt(0).toUpperCase();
  setupNavigation(); setupStudentForms(); await Promise.all([loadStudentDashboard(),loadProfile(),loadDrives(),loadApplications(),loadInterviews(),loadResults(),loadNotifications()]);
}
async function loadStudentSection(name){
  const map={dashboard:loadStudentDashboard,profile:loadProfile,drives:loadDrives,applications:loadApplications,interviews:loadInterviews,results:loadResults,notifications:loadNotifications}; try{if(map[name])await map[name]()}catch(e){toast(e.message,true)}
}
async function loadStudentDashboard(){const d=await api('php/student.php?action=dashboard');const c=d.counts;$('#sDrives').textContent=c.drives;$('#sApplications').textContent=c.applications;$('#sShortlisted').textContent=c.shortlisted;$('#sInterviews').textContent=c.interviews;$('#sSelected').textContent=c.selected;renderRecentDrives();renderRecentNotifications();}
async function loadProfile(){const d=await api('php/student.php?action=get_profile');studentState.profile=d.profile;fillProfile(d.profile);}
function fillProfile(p){['name','reg','email','phone','dob','gender','department','year','cgpa','10','12','skills','certifications'].forEach(k=>{const el=$(`#p${k.charAt(0).toUpperCase()+k.slice(1)}`);if(el){const key=k==='reg'?'register_no':k==='10'?'tenth_percentage':k==='12'?'twelfth_percentage':k;el.value=p[key]??''}});$('#resumeName').textContent=p.resume?`Uploaded: ${p.resume}`:'No resume uploaded.'; updateCompletion(p);}
function updateCompletion(p){const fields=['phone','dob','gender','department','year','cgpa','tenth_percentage','twelfth_percentage','skills','certifications','resume'];const done=fields.filter(k=>String(p[k]??'').trim()!=='').length;const percent=Math.round(done/fields.length*100);$('#profilePercent').textContent=`${percent}%`;$('#profileProgress').style.width=`${percent}%`;}
async function loadDrives(){const d=await api('php/student.php?action=get_drives');studentState.drives=d.drives;renderDrives();renderRecentDrives();}
function renderRecentDrives(){const el=$('#recentDrives');if(!el)return;el.innerHTML=studentState.drives.slice(0,4).map(x=>`<div class="stack-item"><div><strong>${esc(x.company_name)}</strong><small>${esc(x.job_role)} · ${money(x.package)}</small></div><span class="status-pill ${x.eligible?'open':''}">${x.eligible?'Eligible':'Check'}</span></div>`).join('')||'<p class="muted">No drives available.</p>';}
function renderDrives(){const grid=$('#driveGrid');if(!grid)return;const search=($('#driveSearch')?.value||'').toLowerCase();const filter=$('#driveFilter')?.value||'all';let arr=studentState.drives.filter(d=>`${d.company_name} ${d.job_role}`.toLowerCase().includes(search));if(filter==='eligible')arr=arr.filter(d=>d.eligible);if(filter==='applied')arr=arr.filter(d=>d.application);grid.innerHTML=arr.map(d=>`<article class="drive-card"><span class="status-badge ${d.eligible?'open':''}">${d.application?esc(d.application.status):d.eligible?'Eligible':'Not Eligible'}</span><h3>${esc(d.job_role)}</h3><div class="company">${esc(d.company_name)} · ${esc(d.location)}</div><div class="drive-meta"><div><small>Package</small><b>${money(d.package)}</b></div><div><small>Deadline</small><b>${fmtDate(d.deadline)}</b></div><div><small>Min CGPA</small><b>${d.min_cgpa}</b></div><div><small>Openings</small><b>${d.openings}</b></div></div><div class="drive-actions"><button class="btn btn-outline" data-view-drive="${d.drive_id}">View Details</button>${d.application?`<button class="btn btn-outline" disabled>Applied</button>`:d.eligible?`<button class="btn btn-primary" data-apply-drive="${d.drive_id}">Apply Now</button>`:`<button class="btn btn-outline" data-check-drive="${d.drive_id}">Check</button>`}</div></article>`).join('')||'<div class="panel"><p>No matching drives found.</p></div>';$$('[data-view-drive]').forEach(b=>b.onclick=()=>viewDrive(+b.dataset.viewDrive));$$('[data-check-drive]').forEach(b=>b.onclick=()=>viewEligibility(+b.dataset.checkDrive));$$('[data-apply-drive]').forEach(b=>b.onclick=()=>applyDrive(+b.dataset.applyDrive));}
async function viewDrive(id){const d=studentState.drives.find(x=>+x.drive_id===id);if(!d)return;$('#driveModalContent').innerHTML=`<span class="eyebrow">Placement Drive</span><h2>${esc(d.job_role)}</h2><p><b>${esc(d.company_name)}</b> · ${esc(d.location)}</p><div class="check-list"><div class="check-item"><span>Package</span><b>${money(d.package)}</b></div><div class="check-item"><span>Drive Date</span><b>${fmtDateTime(d.drive_date)}</b></div><div class="check-item"><span>Deadline</span><b>${fmtDateTime(d.deadline)}</b></div><div class="check-item"><span>Eligibility</span><b>${esc(d.eligible_departments)} · Year ${d.eligible_year||'Any'}</b></div></div><h3>Job Description</h3><p>${esc(d.job_description||'Not provided.')}</p><h3>Required Skills</h3><p>${esc(d.required_skills||'Not specified.')}</p><h3>Selection Process</h3><p>${esc(d.selection_process||'Not specified.')}</p><h3>Eligibility</h3><p>${d.eligible?'You meet the listed eligibility criteria.':'You are not currently eligible: '+esc(d.eligibility_reasons.join(' '))}</p>`;$('#driveModal').classList.add('show');}
async function viewEligibility(id){try{const d=await post('php/student.php?action=check_eligibility',{drive_id:id});$('#driveModalContent').innerHTML=`<span class="eyebrow">Eligibility Check</span><h2>${d.eligible?'Overall Status: ELIGIBLE':'Overall Status: NOT ELIGIBLE'}</h2><div class="check-list">${d.checks.map(c=>`<div class="check-item ${c.eligible?'ok':'bad'}"><span>${esc(c.label)}</span><b>${c.eligible?'✓ Eligible':'✕ Not Eligible'}</b></div>`).join('')}</div>${d.reasons.length?`<p><b>Reasons:</b> ${esc(d.reasons.join(' '))}</p>`:'<p>You satisfy all listed academic and academic-eligibility rules.</p>'}`;$('#driveModal').classList.add('show')}catch(e){toast(e.message,true)}}
async function applyDrive(id){if(!confirm('Apply for this placement drive?'))return;try{const d=await post('php/student.php?action=apply',{drive_id:id});toast(d.message);await Promise.all([loadDrives(),loadApplications(),loadStudentDashboard()])}catch(e){toast(e.message,true)}}
async function loadApplications(){const d=await api('php/student.php?action=get_applications');studentState.applications=d.applications;renderApplications();fillApplicationSelects();}
function renderApplications(){const el=$('#applicationList');if(!el)return;const stages=['Applied','Shortlisted','Aptitude Cleared','Technical Cleared','HR Cleared','Selected'];el.innerHTML=studentState.applications.map(a=>{const current=a.status==='Rejected'?'Rejected':a.status;const idx=stages.indexOf(current);return `<article class="application-card"><div class="application-head"><div><h3>${esc(a.company_name)}</h3><small>${esc(a.job_role)} · ${money(a.package)}</small></div><span class="status-pill ${statusClass(a.status)}">${esc(a.status)}</span></div><p><small>Applied ${fmtDate(a.applied_date)}</small></p>${a.status==='Rejected'?'<p class="muted">Application closed at the current stage.</p>':`<div class="timeline">${stages.map((s,i)=>`<div class="timeline-step ${i<=idx?'done':''}">${esc(s)}</div>`).join('')}</div>`}</article>`}).join('')||'<div class="panel"><p>No applications yet. Explore Placement Drives to apply.</p></div>';}
async function loadInterviews(){const d=await api('php/student.php?action=get_interviews');studentState.interviews=d.interviews;const el=$('#interviewBody');if(!el)return;el.innerHTML=d.interviews.map(i=>`<tr><td>${esc(i.company_name)}</td><td>${esc(i.job_role)}</td><td>${esc(i.round_name)}</td><td>${fmtDate(i.interview_date)}</td><td>${esc(i.interview_time)}</td><td>${esc(i.mode)}</td><td>${i.meeting_link?`<a class="text-btn" target="_blank" rel="noopener" href="${esc(i.meeting_link)}">Meeting Link</a>`:esc(i.venue||'-')}</td></tr>`).join('')||'<tr><td colspan="7">No interviews scheduled.</td></tr>';}
async function loadResults(){const d=await api('php/student.php?action=get_results');studentState.results=d.results;const el=$('#resultBody');if(!el)return;el.innerHTML=d.results.map(r=>`<tr><td>${esc(r.company_name)}</td><td>${esc(r.job_role)}</td><td>${money(r.package)}</td><td><span class="status-pill ${statusClass(r.result_status)}">${esc(r.result_status)}</span></td><td>${esc(r.remarks||'-')}</td></tr>`).join('')||'<tr><td colspan="5">No results published.</td></tr>';}
async function loadNotifications(){const d=await api('php/student.php?action=get_notifications');studentState.notifications=d.notifications;renderRecentNotifications();const el=$('#notificationList');if(!el)return;el.innerHTML=d.notifications.map(n=>`<article class="notification"><h3>${esc(n.title)}</h3><p>${esc(n.message)}</p><small>${fmtDateTime(n.created_at)}</small></article>`).join('')||'<div class="panel"><p>No notifications.</p></div>';}
function renderRecentNotifications(){const el=$('#recentNotifications');if(!el)return;el.innerHTML=studentState.notifications.slice(0,4).map(n=>`<div class="stack-item"><div><strong>${esc(n.title)}</strong><small>${esc(n.message).slice(0,70)}${n.message.length>70?'…':''}</small></div><small>${fmtDate(n.created_at)}</small></div>`).join('')||'<p>No notifications.</p>';}
function setupStudentForms(){
  $('#profileForm')?.addEventListener('submit',async e=>{e.preventDefault();try{const d=await post('php/student.php?action=update_profile',formObj(e.target));setMsg($('#profileMessage'),d.message);studentState.profile=d.profile;updateCompletion(d.profile);toast('Profile updated.')}catch(err){setMsg($('#profileMessage'),err.message,true)}});
  $('#resumeForm')?.addEventListener('submit',async e=>{e.preventDefault();const file=$('#resumeFile').files[0];if(!file||file.type!=='application/pdf'||file.size>2*1024*1024)return setMsg($('#resumeMessage'),'Select a PDF file up to 2 MB.',true);const fd=new FormData();fd.append('resume',file);try{const d=await api('php/student.php?action=upload_resume',{method:'POST',body:fd});setMsg($('#resumeMessage'),d.message);$('#resumeName').textContent=`Uploaded: ${d.resume}`;$('#resumeFile').value='';studentState.profile.resume=d.resume;updateCompletion(studentState.profile)}catch(err){setMsg($('#resumeMessage'),err.message,true)}});
  $('#driveSearch')?.addEventListener('input',renderDrives);$('#driveFilter')?.addEventListener('change',renderDrives);$('[data-close-modal]')?.addEventListener('click',()=>$('#driveModal').classList.remove('show'));$('#driveModal')?.addEventListener('click',e=>{if(e.target.id==='driveModal')e.currentTarget.classList.remove('show')});
}

let adminState={students:[],companies:[],drives:[],applications:[],interviews:[],results:[],notifications:[]};
async function initAdmin(){const session=await checkSession('admin');if(!session)return;window.dashboardType='admin';$('#adminWelcome').textContent=`Welcome, ${session.name}`;setupNavigation();setupAdminForms();await Promise.all([loadAdminStats(),loadStudents(),loadCompanies(),loadAdminDrives(),loadAdminApplications(),loadAdminInterviews(),loadAdminResults(),loadAdminNotifications(),loadReport()]);}
async function loadAdminSection(name){const map={dashboard:loadAdminStats,students:loadStudents,companies:loadCompanies,drives:loadAdminDrives,applications:loadAdminApplications,interviews:loadAdminInterviews,results:loadAdminResults,reports:loadReport,notifications:loadAdminNotifications};try{if(map[name])await map[name]()}catch(e){toast(e.message,true)}}
async function loadAdminStats(){const d=await api('php/admin.php?action=stats');const s=d.stats;$('#aStudents').textContent=s.students;$('#aCompanies').textContent=s.companies;$('#aDrives').textContent=s.drives;$('#aApplications').textContent=s.applications;$('#aSelected').textContent=s.selected;$('#aRejected').textContent=s.rejected;renderBars($('#statusChart'),[['Selected',s.selected],['Rejected',s.rejected],['Other',Math.max(0,s.applications-s.selected-s.rejected)]]);renderBars($('#departmentChart'),d.department_stats.map(x=>[x.department,x.selected]));}
function renderBars(el,items){if(!el)return;const max=Math.max(1,...items.map(x=>Number(x[1])));el.innerHTML=items.map(x=>`<div class="bar-row"><span>${esc(x[0])}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.round(Number(x[1])/max*100)}%"></div></div><b>${x[1]}</b></div>`).join('')}
async function loadStudents(){const d=await api('php/admin.php?action=students');adminState.students=d.students;renderStudents();}
function renderStudents(){const el=$('#adminStudentBody');if(!el)return;const q=($('#studentSearch')?.value||'').toLowerCase(),dept=$('#studentDeptFilter')?.value||'all',year=$('#studentYearFilter')?.value||'all';const arr=adminState.students.filter(s=>`${s.name} ${s.register_no} ${s.email}`.toLowerCase().includes(q)&& (dept==='all'||s.department===dept)&&(year==='all'||String(s.year)===year));el.innerHTML=arr.map(s=>`<tr><td>${esc(s.register_no)}</td><td>${esc(s.name)}</td><td>${esc(s.email)}</td><td>${esc(s.department)}</td><td>${s.year}</td><td>${s.cgpa??'-'}</td><td>${s.resume?`<a class="text-btn" target="_blank" href="uploads/resumes/${encodeURIComponent(s.resume)}">View</a>`:'-'}</td><td><button class="table-action primary" data-edit-student="${s.student_id}">Edit</button> <button class="table-action" data-view-student="${s.student_id}">View</button> <button class="table-action danger" data-delete-student="${s.student_id}">Delete</button></td></tr>`).join('')||'<tr><td colspan="8">No students found.</td></tr>';$$('[data-edit-student]').forEach(b=>b.onclick=()=>editStudent(+b.dataset.editStudent));$$('[data-view-student]').forEach(b=>b.onclick=()=>viewStudent(+b.dataset.viewStudent));$$('[data-delete-student]').forEach(b=>b.onclick=()=>deleteStudent(+b.dataset.deleteStudent));}
async function editStudent(id){const s=adminState.students.find(x=>+x.student_id===id);if(!s)return;const name=prompt('Student name:',s.name);if(name===null)return;const phone=prompt('Phone:',s.phone||'');if(phone===null)return;const cgpa=prompt('CGPA:',s.cgpa??'');if(cgpa===null)return;try{await post('php/admin.php?action=student_update',{student_id:id,name,phone,cgpa,email:s.email,department:s.department,year:s.year,tenth_percentage:s.tenth_percentage,twelfth_percentage:s.twelfth_percentage,skills:s.skills,certifications:s.certifications});toast('Student updated.');await loadStudents()}catch(e){toast(e.message,true)}}
function viewStudent(id){const s=adminState.students.find(x=>+x.student_id===id);if(s)alert(`Student Profile\n\nName: ${s.name}\nRegister No: ${s.register_no}\nEmail: ${s.email}\nPhone: ${s.phone||'-'}\nDepartment: ${s.department}\nYear: ${s.year}\nCGPA: ${s.cgpa||'-'}\n10th: ${s.tenth_percentage||'-'}%\n12th: ${s.twelfth_percentage||'-'}%\nSkills: ${s.skills||'-'}\nCertifications: ${s.certifications||'-'}`)}
async function deleteStudent(id){if(!confirm('Delete this student? Related applications and interviews will also be removed.'))return;try{await post('php/admin.php?action=student_delete',{student_id:id});toast('Student deleted.');await Promise.all([loadStudents(),loadAdminStats()])}catch(e){toast(e.message,true)}}
async function loadCompanies(){const d=await api('php/admin.php?action=companies');adminState.companies=d.companies;renderCompanies();fillCompanySelect();}
function renderCompanies(){const el=$('#companyBody');if(!el)return;const q=($('#companySearch')?.value||'').toLowerCase();const arr=adminState.companies.filter(c=>`${c.company_name} ${c.industry} ${c.location}`.toLowerCase().includes(q));el.innerHTML=arr.map(c=>`<tr><td>${esc(c.company_name)}</td><td>${esc(c.industry)}</td><td>${esc(c.location)}</td><td>${esc(c.contact_person)}</td><td>${esc(c.email)}</td><td><button class="table-action primary" data-edit-company="${c.company_id}">Edit</button> <button class="table-action danger" data-delete-company="${c.company_id}">Delete</button></td></tr>`).join('')||'<tr><td colspan="6">No companies found.</td></tr>';$$('[data-edit-company]').forEach(b=>b.onclick=()=>fillCompanyForm(+b.dataset.editCompany));$$('[data-delete-company]').forEach(b=>b.onclick=()=>deleteCompany(+b.dataset.deleteCompany));}
function fillCompanySelect(){const el=$('#driveCompany');if(el)el.innerHTML='<option value="">Select company</option>'+adminState.companies.map(c=>`<option value="${c.company_id}">${esc(c.company_name)}</option>`).join('');}
function fillCompanyForm(id){const c=adminState.companies.find(x=>+x.company_id===id);if(!c)return;const f=$('#companyForm');for(const [k,v] of Object.entries(c)){const el=f.elements[k];if(el)el.value=v??''}window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});}
async function deleteCompany(id){if(!confirm('Delete this company? This is only possible if no placement drives use it.'))return;try{await post('php/admin.php?action=company_delete',{company_id:id});toast('Company deleted.');await Promise.all([loadCompanies(),loadAdminStats()])}catch(e){toast(e.message,true)}}
async function loadAdminDrives(){const d=await api('php/admin.php?action=drives');adminState.drives=d.drives;renderAdminDrives();fillCompanySelect();}
function renderAdminDrives(){const el=$('#adminDriveBody');if(!el)return;const q=($('#adminDriveSearch')?.value||'').toLowerCase();const arr=adminState.drives.filter(d=>`${d.company_name} ${d.job_role}`.toLowerCase().includes(q));el.innerHTML=arr.map(d=>`<tr><td>${esc(d.company_name)}</td><td>${esc(d.job_role)}</td><td>${money(d.package)}</td><td>${fmtDateTime(d.drive_date)}</td><td>${fmtDateTime(d.deadline)}</td><td>${esc(d.eligible_departments)} / ${d.eligible_year||'Any'} yr / CGPA ${d.min_cgpa}</td><td><button class="table-action primary" data-edit-drive="${d.drive_id}">Edit</button> <button class="table-action danger" data-delete-drive="${d.drive_id}">Delete</button></td></tr>`).join('')||'<tr><td colspan="7">No drives found.</td></tr>';$$('[data-edit-drive]').forEach(b=>b.onclick=()=>fillDriveForm(+b.dataset.editDrive));$$('[data-delete-drive]').forEach(b=>b.onclick=()=>deleteDrive(+b.dataset.deleteDrive));}
function fillDriveForm(id){const d=adminState.drives.find(x=>+x.drive_id===id);if(!d)return;const f=$('#driveForm');for(const [k,v] of Object.entries(d)){const el=f.elements[k];if(el){let val=v??'';if((k==='drive_date'||k==='deadline')&&val)val=String(val).replace(' ','T').slice(0,16);el.value=val}}window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});}
async function deleteDrive(id){if(!confirm('Delete this drive? It cannot be deleted if applications already exist.'))return;try{await post('php/admin.php?action=drive_delete',{drive_id:id});toast('Drive deleted.');await Promise.all([loadAdminDrives(),loadAdminStats()])}catch(e){toast(e.message,true)}}
async function loadAdminApplications(){const d=await api('php/admin.php?action=applications');adminState.applications=d.applications;renderAdminApplications();fillApplicationSelects();}
function renderAdminApplications(){const el=$('#adminApplicationBody');if(!el)return;const q=($('#applicationSearch')?.value||'').toLowerCase(),filter=$('#applicationStatusFilter')?.value||'all';const arr=adminState.applications.filter(a=>`${a.student_name} ${a.register_no} ${a.company_name}`.toLowerCase().includes(q)&&(filter==='all'||a.status===filter));const statuses=['Applied','Shortlisted','Aptitude Cleared','Technical Cleared','HR Cleared','Selected','Rejected'];el.innerHTML=arr.map(a=>`<tr><td><b>${esc(a.student_name)}</b><br><small>${esc(a.register_no)}</small></td><td>${esc(a.company_name)}</td><td>${esc(a.job_role)}</td><td>${fmtDate(a.applied_date)}</td><td><span class="status-pill ${statusClass(a.status)}">${esc(a.status)}</span></td><td>${a.resume?`<a class="text-btn" target="_blank" href="uploads/resumes/${encodeURIComponent(a.resume)}">View</a>`:'-'}</td><td><select class="status-select" data-app-status="${a.application_id}">${statuses.map(s=>`<option ${s===a.status?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')||'<tr><td colspan="7">No applications found.</td></tr>';$$('[data-app-status]').forEach(s=>s.onchange=()=>updateApplicationStatus(+s.dataset.appStatus,s.value));}
async function updateApplicationStatus(id,status){try{await post('php/admin.php?action=application_status',{application_id:id,status});toast('Application status updated.');await Promise.all([loadAdminApplications(),loadAdminStats(),loadAdminResults()])}catch(e){toast(e.message,true)}}
function fillApplicationSelects(){const opts='<option value="">Select application</option>'+adminState.applications.map(a=>`<option value="${a.application_id}">${esc(a.student_name)} · ${esc(a.company_name)} · ${esc(a.job_role)} (#${a.application_id})</option>`).join('');['interviewApplication','resultApplication'].forEach(id=>{const el=$(`#${id}`);if(el)el.innerHTML=opts});}
async function loadAdminInterviews(){const d=await api('php/admin.php?action=interviews');adminState.interviews=d.interviews;const el=$('#adminInterviewBody');if(!el)return;el.innerHTML=d.interviews.map(i=>`<tr><td>${esc(i.student_name)}</td><td>${esc(i.company_name)}</td><td>${esc(i.round_name)}</td><td>${fmtDate(i.interview_date)}</td><td>${esc(i.interview_time)}</td><td>${esc(i.mode)}</td><td><button class="table-action danger" data-delete-interview="${i.interview_id}">Delete</button></td></tr>`).join('')||'<tr><td colspan="7">No interviews scheduled.</td></tr>';$$('[data-delete-interview]').forEach(b=>b.onclick=()=>deleteInterview(+b.dataset.deleteInterview));}
async function deleteInterview(id){if(!confirm('Delete this interview?'))return;try{await post('php/admin.php?action=interview_delete',{interview_id:id});toast('Interview deleted.');await loadAdminInterviews()}catch(e){toast(e.message,true)}}
async function loadAdminResults(){const d=await api('php/admin.php?action=results');adminState.results=d.results;const el=$('#adminResultBody');if(!el)return;el.innerHTML=d.results.map(r=>`<tr><td>${esc(r.student_name)}</td><td>${esc(r.company_name)}</td><td>${esc(r.job_role)}</td><td><span class="status-pill ${statusClass(r.result_status)}">${esc(r.result_status)}</span></td><td>${esc(r.remarks||'-')}</td></tr>`).join('')||'<tr><td colspan="5">No results recorded.</td></tr>';}
async function loadAdminNotifications(){const d=await api('php/admin.php?action=notifications');adminState.notifications=d.notifications;const el=$('#adminNotificationList');if(!el)return;el.innerHTML=d.notifications.map(n=>`<article class="notification"><div class="panel-head"><div><h3>${esc(n.title)}</h3><p>${esc(n.message)}</p></div><button class="table-action danger" data-delete-notification="${n.notification_id}">Delete</button></div><small>${fmtDateTime(n.created_at)}</small></article>`).join('')||'<div class="panel"><p>No notifications.</p></div>';$$('[data-delete-notification]').forEach(b=>b.onclick=()=>deleteNotification(+b.dataset.deleteNotification));}
async function deleteNotification(id){if(!confirm('Delete notification?'))return;try{await post('php/admin.php?action=notification_delete',{notification_id:id});toast('Notification deleted.');await loadAdminNotifications()}catch(e){toast(e.message,true)}}
async function loadReport(){const d=await api('php/admin.php?action=report');const s=d.stats;['students','companies','drives','applications','selected'].forEach(k=>{const el=$(`#r${k.charAt(0).toUpperCase()+k.slice(1)}`);if(el)el.textContent=s[k]});const db=$('#deptReportBody');if(db)db.innerHTML=d.department.map(x=>`<tr><td>${esc(x.department)}</td><td>${x.students}</td><td>${x.selected}</td></tr>`).join('');const cb=$('#companyReportBody');if(cb)cb.innerHTML=d.company.map(x=>`<tr><td>${esc(x.company_name)}</td><td>${x.selected}</td></tr>`).join('');renderBars($('#reportStatusChart'),d.status.map(x=>[x.status,x.total]));}
function setupAdminForms(){
  $('#studentSearch')?.addEventListener('input',renderStudents);$('#studentDeptFilter')?.addEventListener('change',renderStudents);$('#studentYearFilter')?.addEventListener('change',renderStudents);$('#companySearch')?.addEventListener('input',renderCompanies);$('#adminDriveSearch')?.addEventListener('input',renderAdminDrives);$('#applicationSearch')?.addEventListener('input',renderAdminApplications);$('#applicationStatusFilter')?.addEventListener('change',renderAdminApplications);
  $('#companyForm')?.addEventListener('submit',async e=>{e.preventDefault();try{const d=await post('php/admin.php?action=company_save',formObj(e.target));setMsg($('#companyMessage'),d.message);e.target.reset();$('#companyId').value='';await Promise.all([loadCompanies(),loadAdminStats()])}catch(err){setMsg($('#companyMessage'),err.message,true)}});$('#companyReset')?.addEventListener('click',()=>{$('#companyForm').reset();$('#companyId').value=''});
  $('#driveForm')?.addEventListener('submit',async e=>{e.preventDefault();try{const d=await post('php/admin.php?action=drive_save',formObj(e.target));setMsg($('#driveMessage'),d.message);e.target.reset();$('#driveId').value='';$('#driveForm [name="eligible_departments"]').value='ALL';$('#driveForm [name="eligible_year"]').value='0';await Promise.all([loadAdminDrives(),loadAdminStats()])}catch(err){setMsg($('#driveMessage'),err.message,true)}});$('#driveReset')?.addEventListener('click',()=>{$('#driveForm').reset();$('#driveId').value='';$('#driveForm [name="eligible_departments"]').value='ALL';});
  $('#interviewForm')?.addEventListener('submit',async e=>{e.preventDefault();try{const d=await post('php/admin.php?action=interview_save',formObj(e.target));setMsg($('#interviewMessage'),d.message);e.target.reset();$('#interviewId').value='';await loadAdminInterviews()}catch(err){setMsg($('#interviewMessage'),err.message,true)}});$('#interviewReset')?.addEventListener('click',()=>{$('#interviewForm').reset();$('#interviewId').value=''});
  $('#resultForm')?.addEventListener('submit',async e=>{e.preventDefault();try{const d=await post('php/admin.php?action=result_save',formObj(e.target));setMsg($('#resultMessage'),d.message);e.target.reset();await Promise.all([loadAdminResults(),loadAdminApplications(),loadAdminStats(),loadReport()])}catch(err){setMsg($('#resultMessage'),err.message,true)}});
  $('#notificationForm')?.addEventListener('submit',async e=>{e.preventDefault();try{const d=await post('php/admin.php?action=notification_save',formObj(e.target));setMsg($('#notificationMessage'),d.message);e.target.reset();await loadAdminNotifications()}catch(err){setMsg($('#notificationMessage'),err.message,true)}});
  $('#printReport')?.addEventListener('click',()=>window.print());
}

(async function boot(){
  setupAuth();setupPublic();
  if(document.body.classList.contains('dashboard-page')){if(location.pathname.endsWith('admin-dashboard.html'))await initAdmin();else await initStudent();}
})();
